version: "3.9"
name: default
services:
  nginx:
    container_name: nginx_${PROJECT_NAME}
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    links:
      - php
      - db

  php:
    container_name: php_${PROJECT_NAME}
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
    links:
      - db

  db:
    container_name: mysql_${PROJECT_NAME}
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_default:/var/lib/mysql:rw
    ports:
      - 3306:3306

volumes:
  db_default:
